spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consumables?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: LIZHONGJIE199608

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

server:
  tomcat:
    uri-encoding: utf-8
  port: 8888

security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123


